apiVersion: v1
kind: ServiceAccount
metadata:
  name: constellation-csi-controller
  namespace: {{ .Release.Namespace }}
  labels: {{- include "csi.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: constellation-csi-node
  namespace: {{ .Release.Namespace }}
  labels: {{- include "csi.labels" . | nindent 4 }}
